Update README.md. AWESOME!
geoffreyzgoog/step-starter pull request #1
Opened 2020-06-23 02:35 UTC by geoffreyzgoog

Everything is awesome...

2020-06-29 16:23 UTC, GeffZh requested changes

2020-06-29 16:23 UTC, GeffZh commented on README.md
> +This repo contains MY FREAKIN' AWESOME projects.
Not that awesome to me.

2020-06-30 03:14 UTC, geoffreyzgoog commented on README.md
> +This repo contains MY FREAKIN' AWESOME projects.
Updated.

2020-06-30 03:15 UTC, GeffZh approved these changes

2020-06-30 03:16 UTC, merged